---
# tasks file for weaviate

- name: 清除旧容器与部署目录
  shell: 'docker-compose -f {{ OPT_PATH }}/{{ WEAVIATE_CONTAINER_NAME }}/docker-compose.yaml rm -fsva; rm -rf {{ OPT_PATH }}/{{ WEAVIATE_CONTAINER_NAME }}'

- name: 预处理 - 创建部署目录
  shell: '[[ ! -d "{{ OPT_PATH }}/{{ WEAVIATE_CONTAINER_NAME }}" ]] && mkdir -vp {{ OPT_PATH }}/{{ WEAVIATE_CONTAINER_NAME }}'

- name: 编排 docker-compose.yaml
  template: src=docker-compose.yaml.j2 dest={{ OPT_PATH }}/{{ WEAVIATE_CONTAINER_NAME }}/docker-compose.yaml

- name: 部署服务
  shell: 'docker-compose -f  {{ OPT_PATH }}/{{ WEAVIATE_CONTAINER_NAME }}/docker-compose.yaml up -d'